[package]
name = "findorad"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abcf = { git = "ssh://git@github.com/FindoraNetwork/abcf" }
abcf-node = { git = "ssh://git@github.com/FindoraNetwork/abcf" }
abcf-sdk = { git = "ssh://git@github.com/FindoraNetwork/abcf", features = ["http"] }
bs3 = { git = "ssh://git@github.com/FindoraNetwork/bs3", features = ["sled-backend"] }
env_logger = "0.9.0"
async-trait = "0.1.51"
sha3 = "0.9.1"
digest = "0.9.0"
serde_json = "1.0.68"
serde = "1.0.130"
libfindora = { path = "../libfindora" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", branch = "feat-refactor" }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.2"

[lib]
name = "findorad_lib"
path = "src/lib.rs"
