[workspace]
members = [
    "findorad",
    "libfindora",
    "libfn",
    "cli",
    "modules/utxo",
    "modules/coinbase",
    "modules/staking",
    "modules/rewards",
    "modules/fee",
    "modules/asset",
    "modules/evm",
    "modules/governance",
    "web3",
    "library/librewards",
]
