[package]
name = "fn"
authors = ["FindoraNetwork"]
version = "0.1.0"
edition = "2021"
description = "Findora Network command line tool."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libfn = { path = "../libfn" }
clap = { version = "3.0.0-rc.4", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
serde = "1.0.130"
toml = "0.5.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
anyhow = "1.0"
home = "0.5.3"
