[package]
name = "fn"
authors = ["FindoraNetwork"]
version = "0.1.0"
edition = "2018"
description = "Findora Network command line tool."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = "1.0.130"
toml = "0.5.8"
