[package]
name = "fn"
authors = ["FindoraNetwork"]
version = "0.1.0"
edition = "2021"
description = "Findora Network command line tool."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-rc.4", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = "1.0.130"
toml = "0.5.8"
zei = { git = "https://github.com/tiannian/zei.git", branch = "feat-refactor-address-v1" }
libfindora = { path = "../libfindora" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tokio = { version = "1", features = ["full"] }
abcf = { git = "https://github.com/FindoraNetwork/abcf.git" }
abcf-sdk = { git = "https://github.com/FindoraNetwork/abcf.git", features = ["http"] }
base64 = "0.10"
sha3 = "0.9.1"
hex-literal = "0.3.1"
hex = "0.4.3"
reqwest = { version = "0.11", features = ["json"]}
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.2"
bech32 = "0.8.1"
bip0039 = "0.8.0"
ed25519-dalek-bip32 = { git = "https://github.com/FindoraNetwork/ed25519-dalek-bip32", branch = "feat-allow-nohardened" }
libfn = { path = "../libfn" }
fm-utxo = { path = "../modules/utxo" }
anyhow = "1.0"
