[package]
name = "fn"
authors = ["FindoraNetwork"]
version = "0.1.0"
edition = "2018"
description = "Findora Network command line tool."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
env_logger = "0.9.0"
log = "0.4.14"
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = "1.0.130"
toml = "0.5.8"
zei = { git = "ssh://git@github.com/tiannian/zei", branch = "feat-refactor" }
libfindora = { path = "../libfindora" }
findorad = { path = "../findorad" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tokio = { version = "1", features = ["full"] }
abcf-sdk = { git = "ssh://git@github.com/FindoraNetwork/abcf", features = ["http"] }
base64 = "0.10"
sha3 = "0.9.1"
hex-literal = "0.3.1"
hex = "0.4.3"
reqwest = { version = "0.11", features = ["json"]}
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.2"
bech32 = "0.8.1"
bip0039 = "0.8.0"
ed25519-dalek-bip32 = { git = "https://github.com/FindoraNetwork/ed25519-dalek-bip32", branch = "feat-allow-nohardened" }

